// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Reprocessing from "reprocessing/src/Reprocessing.bs.js";
import * as Reprocessing_Env from "reprocessing/src/Reprocessing_Env.bs.js";
import * as Reprocessing_Draw from "reprocessing/src/Reprocessing_Draw.bs.js";
import * as Reprocessing_Constants from "reprocessing/src/Reprocessing_Constants.bs.js";

function Test$TestComponent(Props) {
  return React.createElement("div", undefined, "Fuback Das Ding");
}

var TestComponent = {
  make: Test$TestComponent
};

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(Test$TestComponent, {}), root);
}

function setup(env) {
  return Reprocessing_Env.size(200, 200, env);
}

function draw(_state, env) {
  Reprocessing_Draw.background(Reprocessing_Constants.black, env);
  Reprocessing_Draw.fill(Reprocessing_Constants.red, env);
  return Reprocessing_Draw.rect([
              50,
              50
            ], 100, 100, env);
}

Reprocessing.run(setup, undefined, draw, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);

export {
  TestComponent ,
  setup ,
  draw ,
  
}
/* root Not a pure module */
